on: [push, pull_request]

name: unit-tests

jobs:
  unit-tests:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: "4.1.0"}
          - {os: macOS-latest,   r: "4.1.0"}
          - {os: ubuntu-20.04,   r: "4.1.0"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_UPGRADE: never
      VDIFFR_RUN_TESTS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: jasp-stats/jasp-actions/setup-test-env@master
      
      - name: Make sure igraph is installed from source
        if: ${{ runner.os == 'Linux' }}
        run: install.packages("igraph", type = "source", repos = "https://cloud.r-project.org/")
        shell: Rscript {0}


      - name: Run unit tests
        run: source("tests/testthat.R")
        shell: Rscript {0}
